version: 2
jobs:
   one:
     docker:
       -image: cing/ruby:2.6.8
        auth:
         username: deepalimalik
         password: $DOCKERRHUB_PASSWORD
      steps:
        - checkout
        - run: echo "A first hello"
        - run: sleep 25
    two:
      docker:
        - image: cing/ruby:3.0.2
          auth:
          username: deepalimalik
          password: $DOCKERRHUB_PASSWORD
      steps:
        - checkout
        - run: echo "A more familier hi"
        - run: sleep 15
  workflows:
    version: 2
    one_and_two:
      jobs:
        -one
        -two


